name: Wolfer
favicon: null
layout_spectrum: 0.08262
typography_spectrum: 0.90821
title: Wolfer Melodic Hardcore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202830'
    - '#ffffff'
    - '#2e3e4d'
    - '#969fa5'
    - '#7a7c7b'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
